export default function Head() {
	return (
		<>
			<title>Email Converter: Hubspot to Constant Contact</title>
			<meta
				content='width=device-width, initial-scale=1'
				name='viewport'
			/>
			<meta
				name='description'
				content='Generated by create next app'
			/>
			<link rel='icon' href='/favicon.ico' />
		</>
	);
}
